In [1]:
import numpy as np

In [5]:
#1
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
#2
a = np.array([[0,1,2],
             [3,4,5],
             [6,7,8]])

b = np.arange(9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
#3
id_matrix = np.eye(3)
id_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
#4
arr_3_3_3 = np.random.random((3,3,3))
arr_3_3_3

array([[[0.10410581, 0.39818416, 0.59515708],
        [0.4617328 , 0.7968797 , 0.77013744],
        [0.69606027, 0.74897332, 0.91123263]],

       [[0.42172287, 0.14639207, 0.70249699],
        [0.19801811, 0.88693435, 0.56913853],
        [0.36296923, 0.14628829, 0.00760863]],

       [[0.40235319, 0.46618842, 0.32421861],
        [0.25624724, 0.61468941, 0.21728426],
        [0.47208957, 0.0337423 , 0.63144747]]])

In [18]:
#5
array_10x10 = np.random.random((10, 10))
min_value = np.min(array_10x10)
max_value = np.max(array_10x10)

print(array_10x10)
print(min_value)
print(max_value)

[[0.22809061 0.54843696 0.47403463 0.71792572 0.29458986 0.76871971
  0.46796233 0.91188824 0.72134747 0.5961815 ]
 [0.74043539 0.89401379 0.07658555 0.56613425 0.47939434 0.93603513
  0.53026972 0.50007924 0.37630866 0.0055796 ]
 [0.63858996 0.31415771 0.84338225 0.40773114 0.44875599 0.03078545
  0.06730274 0.19273341 0.59738721 0.87666253]
 [0.02693564 0.63526501 0.96791003 0.26252746 0.60321026 0.23652227
  0.9101541  0.98836879 0.89145143 0.88174196]
 [0.62361409 0.71466275 0.96260946 0.97915366 0.15863544 0.52171974
  0.91831078 0.88680236 0.71708032 0.50255152]
 [0.89241962 0.6476054  0.95049174 0.10949682 0.0599474  0.58462001
  0.16867396 0.05196829 0.81692968 0.21870904]
 [0.12947252 0.10438785 0.13170333 0.97071328 0.30827509 0.64848503
  0.78706058 0.19854913 0.84648234 0.90121792]
 [0.23836856 0.71420421 0.95065993 0.35319291 0.73330789 0.44367205
  0.22723673 0.79863329 0.46968259 0.85907001]
 [0.38596619 0.94093048 0.91122374 0.64892823 0.74949341 0.28770406
  0.2485604 

In [19]:
#6
random_vector_30 = np.random.random(30)
mean_value = np.mean(random_vector_30)
print(random_vector_30)
print(mean_value)

[0.8164262  0.96359567 0.0579238  0.89737163 0.70724731 0.82922086
 0.32323207 0.48195419 0.32540812 0.76190218 0.87744599 0.51806495
 0.80264064 0.82006563 0.97315079 0.09412331 0.38288172 0.40478852
 0.28248091 0.46316517 0.51496062 0.50690699 0.21023602 0.98846175
 0.75503495 0.05622806 0.29199847 0.05339995 0.16887682 0.00808051]
0.5112424590269009


In [23]:
#7
matrix_5x5 = np.random.random((5, 5))
normalized_matrix  = (matrix_5x5 - np.min(matrix_5x5)) / (np.max(matrix_5x5)-np.min(matrix_5x5))
print(matrix_5x5)
print(normalized_matrix)

[[0.96104523 0.27317965 0.87615341 0.28358872 0.71004568]
 [0.42477323 0.95953813 0.67746852 0.35527881 0.40210452]
 [0.0724734  0.79222666 0.07534244 0.0247963  0.46919753]
 [0.61837802 0.95117751 0.60423687 0.52114479 0.16052438]
 [0.67237017 0.55047276 0.57482846 0.22681583 0.10198913]]
[[1.         0.26529627 0.90932772 0.27641411 0.73190938]
 [0.42721216 0.99839028 0.69711398 0.35298573 0.40299989]
 [0.05092353 0.81968623 0.05398793 0.         0.47466139]
 [0.63399989 0.98946037 0.61889584 0.53014585 0.14497007]
 [0.69166848 0.56147082 0.58748495 0.21577544 0.08244904]]


In [34]:
#8
matirx_5x3 = np.random.randint(1,10, (5,3))
matirx_3x2 = np.random.randint(1,10, (3,2))
matrix_mult = np.dot(matirx_5x3, matirx_3x2)
print(matrix_mult)

[[51 58]
 [53 57]
 [65 56]
 [59 52]
 [36 24]]


In [36]:
#9
matrix_A = np.random.randint(1, 9, (3, 3))
matrix_B = np.random.randint(1, 9, (3, 3))
dot_product_3x3 = np.dot(matrix_A, matrix_B)
print(dot_product_3x3)

[[41 45 65]
 [33 40 42]
 [57 69 76]]


In [28]:
#10
matrix_4x4 = np.random.randint(1,10,(4, 4))
transpose_4x4 = matrix_4x4.T
print(matrix_4x4)
print(transpose_4x4)

[[1 1 9 6]
 [6 4 3 3]
 [1 2 8 2]
 [1 4 6 7]]
[[1 6 1 1]
 [1 4 2 4]
 [9 3 8 6]
 [6 3 2 7]]


In [44]:
#11

matrix_4x4_det = np.random.randint(1,10,(4,4))
cal_det = np.linalg.det(matrix_4x4_det)
print(f"{cal_det:.2f}")

130.00


In [47]:
#12
matrix_A_3x4 = np.random.random((3, 4))
matrix_B_4x3 = np.random.random((4, 3))
matrix_product_A_B = np.dot(matrix_A_3x4, matrix_B_4x3)
print(matrix_product_A_B)

[[1.21870666 1.13562766 0.31575438]
 [1.07426725 1.03585019 0.27438771]
 [1.36670588 1.38967222 0.34258954]]


In [51]:
#13
matrix_3x3_rand = np.random.random((3, 3))
vector_3x1 = np.random.random((3, 1))
matrix_vector_product = np.dot(matrix_3x3_rand, vector_3x1)
print(matrix_vector_product)

[[1.23313851]
 [0.73560146]
 [0.98281404]]


In [52]:
#14
A = np.random.random((3, 3))
b = np.random.random((3, 1))
x_solution = np.linalg.solve(A, b)
print(x_solution)

[[  0.96969011]
 [-26.52841891]
 [ 37.81260289]]


In [56]:
#15
matrix_5x5_sums = np.random.randint(1,10,(5, 5))
print(matrix_5x5_sums, "\n")
row_sums = np.sum(matrix_5x5_sums, axis=1)
print(row_sums, "\n")
column_sums = np.sum(matrix_5x5_sums, axis=0)
print(column_sums)

[[6 1 3 1 7]
 [3 6 5 4 7]
 [1 7 2 9 2]
 [6 2 9 6 1]
 [2 5 6 9 7]] 

[18 25 21 24 29] 

[18 21 25 29 24]
